Imigize.define('Imigize.integration.main.shop.SportmasterCompatibility', {

    extend: 'Imigize.integration.imigize.compatibility.Compatibility',

    MODEL_COMPATIBILITY:    'Imigize.integration.main.shop.SportmasterCompatibilityModel',
    VIEW_COMPATIBILITY:     'Imigize.integration.main.shop.SportmasterCompatibilityDefault',
    VIEW_MINI_RESULT:       'Imigize.integration.views.result.ResultSportmaster',
    VIEW_SECTOR:            'Imigize.integration.views.sector.SectorSportmaster',
    VIEW_PART_SIZE_SELECT:  'Imigize.integration.views.sizeSelector.SizeSelectorSportmaster',
    VIEW_FULL_ENTER:        'Imigize.integration.views.enter.EnterSportmaster',
    VIEW_FULL_LANDING:      'Imigize.integration.views.landing.LandingSportmaster',
    VIEW_MINI_NEED_AUTH:    'Imigize.integration.views.start.StartSportmaster',
    VIEW_FULL_DEFAULT:      'Imigize.integration.imigize.compatibility.view.full.CompatibilitySportmaster',
    VIEW_PART_RESULT:       'Imigize.integration.views.resultPart.ResultSportmaster',
    VIEW_PART_AUTH:         'Imigize.integration.views.authPanel.AuthPanelSportmaster',
    VIEW_FULL_ABOUT_COMP:   'Imigize.integration.views.sector.AboutCompatibilitySportmaster',
    VIEW_MINI_PRODUCT_404:  'Imigize.integration.views.productNotFound.ProductNotFoundSportmaster',
    VIEW_POPUP_CLOSE:       'Imigize.integration.views.PopupWindowCloseSportmaster',
    ROUTER:                 'Imigize.integration.main.shop.SportmasterDefaultRouter',
    VIEW_WINDOW_ENTER:      'Imigize.integration.main.shop.SportmasterCompatibilityWindowDefault',
    VIEW_RADIO_BTN:         'Imigize.integration.views.radioBtn.RadioBtnSportmaster',
    VIEW_FILTER_MODEL:      'Imigize.integration.main.shop.SportmasterFilterModel',
    VIEW_RESULT_CATALOG:    'Imigize.integration.views.resultCatalog.ResultCatalogSportmaster',
    VIEW_BANNER_CATALOG:    'Imigize.integration.views.bannerCatalog.BannerCatalogSportmaster',
    VIEW_RESULT_BUSKET:     'Imigize.integration.views.resultBusket.ResultBusketSportmaster',
    VIEW_BTN_OPEN_COMFORT:  'Imigize.integration.views.ComfortFoot.BtnOpenSportmaster',
    VIEW_COMFORT_MODEL:     'Imigize.integration.views.ComfortFoot.ComfortModelSportmaster',
    VIEW_PRODUCT_ITEM:      'Imigize.integration.main.shop.SportmasterProductItem',
    VIEW_MINI_EMPTY:        'Imigize.integration.views.empty.EmptySportmaster',
});